el1 = driver.find_element_by_id("android:id/button2")
el1.click()
el2 = driver.find_element_by_id("android:id/decor_content_parent")
el2.click()
el3 = driver.find_element_by_id("android:id/decor_content_parent")
el3.click()
el4 = driver.find_element_by_id("android:id/decor_content_parent")
el4.click()
driver.back()
driver.back()
driver.back()
driver.back()
driver.back()
driver.back()
driver.back()
driver.back()
el5 = driver.find_element_by_id("com.sec.android.app.launcher:id/active")
el5.click()
el6 = driver.find_element_by_id("com.sec.android.app.launcher:id/inactive")
el6.click()
driver.back()
driver.back()
el7 = driver.find_element_by_xpath("//android.widget.FrameLayout[@content-desc=\"Internet\"]/android.widget.ImageView")
el7.click()
el8 = driver.find_element_by_id("android:id/alertTitle")
el8.click()
el9 = driver.find_element_by_id("android:id/button2")
el9.click()
el10 = driver.find_element_by_id("android:id/button2")
el10.click()
el11 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.view.View")
el11.click()
el12 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.view.View")
el12.click()
el13 = driver.find_element_by_accessibility_id("Search or enter URL")
el13.send_keys("https://photos.google.com/?tab=uq1&pageId=none")
el14 = driver.find_element_by_accessibility_id("Search or enter URL")
el14.click()
el15 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.view.View")
el15.click()
el16 = driver.find_element_by_id("com.sec.android.app.sbrowser:id/search_engine_spinner_button")
el16.click()
el17 = driver.find_element_by_id("com.sec.android.app.sbrowser:id/dropdown_check")
el17.click()
driver.back()
el18 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.view.View")
el18.click()
el19 = driver.find_element_by_accessibility_id("Search or enter URL")
el19.send_keys("https://photos.google.com/")
el19.send_keys("submit")
el20 = driver.find_element_by_accessibility_id("Refresh")
el20.click()
el21 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.view.View")
el21.click()
el22 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.view.View")
el22.click()
el23 = driver.find_element_by_id("com.sec.android.app.sbrowser:id/bottombar_option_menu")
el23.click()
el24 = driver.find_element_by_xpath("//android.widget.RelativeLayout[@content-desc=\"Add-ons, Button\"]/android.widget.RelativeLayout/android.widget.LinearLayout[1]/android.widget.ImageView")
el24.click()
el25 = driver.find_element_by_accessibility_id("Navigate up")
el25.click()
el26 = driver.find_element_by_id("com.sec.android.app.sbrowser:id/home_icon")
el26.click()
el27 = driver.find_element_by_id("com.sec.android.app.sbrowser:id/backward_icon")
el27.click()
el27.click()
el27.click()
el28 = driver.find_element_by_accessibility_id("Search or enter URL")
el28.click()
el29 = driver.find_element_by_accessibility_id("Search or enter URL")
el29.send_keys("")
el30 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.view.View")
el30.click()
el31 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout")
el31.click()
TouchAction(driver).tap(x=776, y=282).perform()
TouchAction(driver).tap(x=296, y=1738).perform()
TouchAction(driver).tap(x=930, y=322).perform()
TouchAction(driver).tap(x=758, y=1856).perform()
TouchAction(driver).tap(x=717, y=430).perform()
TouchAction(driver)   .press(x=750, y=1021)   .move_to(x=250, y=1026)   .release()   .perform()
    
TouchAction(driver)   .press(x=419, y=1177)   .move_to(x=126, y=1163)   .release()   .perform()
    
TouchAction(driver)   .press(x=537, y=1607)   .move_to(x=604, y=943)   .release()   .perform()
    
TouchAction(driver)   .press(x=476, y=1110)   .move_to(x=481, y=1746)   .release()   .perform()
    
TouchAction(driver).tap(x=89, y=312).perform()
TouchAction(driver).tap(x=395, y=1690).perform()
TouchAction(driver).tap(x=989, y=1577).perform()
TouchAction(driver).tap(x=967, y=293).perform()
TouchAction(driver).tap(x=586, y=1843).perform()
TouchAction(driver).tap(x=964, y=159).perform()
driver.back()
TouchAction(driver).tap(x=322, y=771).perform()
TouchAction(driver).tap(x=400, y=776).perform()
el32 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout")
el32.send_keys("elizabethblands@gmail.com")
TouchAction(driver).tap(x=983, y=1991).perform()
TouchAction(driver).tap(x=379, y=768).perform()
el32.click()
TouchAction(driver).tap(x=210, y=766).perform()
el33 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout")
el33.click()
el33.send_keys("elizabethblands@gmail.com")
TouchAction(driver).tap(x=830, y=1421).perform()
el33.click()
TouchAction(driver).tap(x=860, y=1419).perform()
TouchAction(driver)   .press(x=551, y=1093)   .move_to(x=1064, y=1099)   .release()   .perform()
    
TouchAction(driver)   .press(x=1021, y=1695)   .move_to(x=35, y=1701)   .release()   .perform()
    
TouchAction(driver)   .press(x=672, y=1413)   .move_to(x=986, y=1389)   .release()   .perform()
    
driver.back()
driver.back()
driver.back()
driver.back()
driver.back()
TouchAction(driver).tap(x=484, y=1037).perform()
TouchAction(driver).tap(x=153, y=707).perform()
el34 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.view.View/android.view.View[1]/android.view.View[1]/android.widget.EditText")
el34.click()
TouchAction(driver).tap(x=285, y=1547).perform()
TouchAction(driver).tap(x=954, y=1655).perform()
TouchAction(driver).tap(x=793, y=1531).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=476, y=720).perform()
TouchAction(driver).tap(x=220, y=1840).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=723, y=715).perform()
TouchAction(driver).tap(x=113, y=1668).perform()
TouchAction(driver).tap(x=656, y=1803).perform()
TouchAction(driver).tap(x=336, y=1260).perform()
TouchAction(driver).tap(x=637, y=1813).perform()
TouchAction(driver).tap(x=981, y=1676).perform()
TouchAction(driver).tap(x=129, y=1650).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=602, y=717).perform()
TouchAction(driver).tap(x=758, y=1830).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=626, y=701).perform()
TouchAction(driver).tap(x=234, y=1658).perform()
TouchAction(driver).tap(x=349, y=1950).perform()
TouchAction(driver).tap(x=997, y=1821).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=776, y=712).perform()
TouchAction(driver).tap(x=997, y=1824).perform()
TouchAction(driver).tap(x=339, y=1684).perform()
TouchAction(driver).tap(x=242, y=1676).perform()
TouchAction(driver).tap(x=347, y=1959).perform()
TouchAction(driver).tap(x=341, y=1969).perform()
TouchAction(driver).tap(x=1018, y=1835).perform()
TouchAction(driver).tap(x=553, y=1674).perform()
TouchAction(driver).tap(x=728, y=1281).perform()
TouchAction(driver).tap(x=911, y=1088).perform()
TouchAction(driver).tap(x=881, y=1921).perform()
TouchAction(driver).tap(x=999, y=1803).perform()
TouchAction(driver).tap(x=956, y=1684).perform()
TouchAction(driver).tap(x=803, y=1494).perform()
TouchAction(driver).tap(x=228, y=1797).perform()
TouchAction(driver).tap(x=140, y=1644).perform()
TouchAction(driver).tap(x=400, y=1515).perform()
TouchAction(driver).tap(x=336, y=1647).perform()
TouchAction(driver).tap(x=86, y=1827).perform()
TouchAction(driver).tap(x=172, y=1534).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=564, y=782).perform()
TouchAction(driver).tap(x=126, y=1674).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=459, y=771).perform()
TouchAction(driver).tap(x=387, y=1537).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=583, y=733).perform()
TouchAction(driver).tap(x=930, y=736).perform()
TouchAction(driver).tap(x=336, y=1679).perform()
TouchAction(driver).tap(x=680, y=1424).perform()
TouchAction(driver).tap(x=613, y=1421).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=720, y=795).perform()
TouchAction(driver).tap(x=889, y=1394).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=677, y=758).perform()
TouchAction(driver).tap(x=322, y=1647).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=596, y=739).perform()
TouchAction(driver).tap(x=277, y=1502).perform()
TouchAction(driver).tap(x=177, y=1507).perform()
TouchAction(driver).tap(x=83, y=2034).perform()
TouchAction(driver).tap(x=75, y=1668).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=895, y=1937).perform()
TouchAction(driver).tap(x=879, y=1945).perform()
TouchAction(driver).tap(x=556, y=1805).perform()
TouchAction(driver).tap(x=881, y=1934).perform()
TouchAction(driver).tap(x=889, y=1926).perform()
TouchAction(driver).tap(x=709, y=623).perform()
driver.back()
TouchAction(driver).tap(x=946, y=314).perform()
TouchAction(driver).tap(x=913, y=306).perform()
TouchAction(driver).tap(x=242, y=787).perform()
TouchAction(driver).tap(x=897, y=1255).perform()
driver.back()
TouchAction(driver).tap(x=492, y=790).perform()
TouchAction(driver).tap(x=258, y=1531).perform()
TouchAction(driver).tap(x=948, y=1679).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=435, y=830).perform()
TouchAction(driver).tap(x=801, y=1547).perform()
TouchAction(driver).tap(x=231, y=1792).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=551, y=1993).perform()
TouchAction(driver).tap(x=776, y=287).perform()
TouchAction(driver).tap(x=782, y=301).perform()
TouchAction(driver).tap(x=287, y=1725).perform()
TouchAction(driver).tap(x=457, y=1854).perform()
TouchAction(driver).tap(x=387, y=704).perform()
TouchAction(driver).tap(x=451, y=701).perform()
TouchAction(driver).tap(x=279, y=1518).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=674, y=763).perform()
TouchAction(driver).tap(x=959, y=1674).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=793, y=731).perform()
TouchAction(driver).tap(x=793, y=1529).perform()
TouchAction(driver).tap(x=578, y=1257).perform()
TouchAction(driver).tap(x=895, y=1080).perform()
TouchAction(driver).tap(x=811, y=1924).perform()
TouchAction(driver).tap(x=940, y=736).perform()
TouchAction(driver).tap(x=263, y=750).perform()
TouchAction(driver).tap(x=991, y=1824).perform()
TouchAction(driver).tap(x=946, y=1698).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=938, y=733).perform()
TouchAction(driver).tap(x=927, y=744).perform()
TouchAction(driver).tap(x=809, y=1521).perform()
TouchAction(driver).tap(x=226, y=1803).perform()
TouchAction(driver).tap(x=121, y=1636).perform()
TouchAction(driver).tap(x=387, y=1510).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=489, y=782).perform()
TouchAction(driver).tap(x=357, y=1690).perform()
TouchAction(driver).tap(x=83, y=1813).perform()
TouchAction(driver).tap(x=172, y=1539).perform()
TouchAction(driver).tap(x=126, y=1682).perform()
TouchAction(driver).tap(x=373, y=1539).perform()
TouchAction(driver).tap(x=325, y=1676).perform()
TouchAction(driver).tap(x=690, y=1410).perform()
TouchAction(driver).tap(x=613, y=1397).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=639, y=779).perform()
TouchAction(driver).tap(x=903, y=1405).perform()
TouchAction(driver).tap(x=330, y=1652).perform()
TouchAction(driver).tap(x=290, y=1515).perform()
TouchAction(driver).tap(x=null, y=null).perform()
TouchAction(driver).tap(x=656, y=733).perform()
TouchAction(driver).tap(x=167, y=1553).perform()
TouchAction(driver).tap(x=110, y=1953).perform()
TouchAction(driver).tap(x=81, y=1676).perform()
TouchAction(driver).tap(x=862, y=1085).perform()
TouchAction(driver).tap(x=881, y=1921).perform()
TouchAction(driver).tap(x=830, y=1899).perform()